FROM node:lts

USER node
RUN mkdir /home/node/h5p-nodejs-library
WORKDIR /home/node/h5p-nodejs-library
COPY --chown=node:node . ./
RUN npm run --prefix packages/h5p-rest-example-client build

EXPOSE 8080
CMD [ "node", "build/index.js" ]
